version: '3'

services:
  mysql-standalone:
    image: 'mysql:5.7'
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=todo1
    ports:
      - "3307:3306"

  nginx:
    image: 'nginx:stable-alpine'
    restart: always
    ports:
      - '8082:8080'
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  springboot-docker-container:
    image: springboot-docker-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/todo1
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    restart: always
    depends_on:
      - mysql-standalone
      - nginx